#!/usr/bin/env bash
echo ""
echo "=========================================================="
echo "  POST-COMMIT: Run subagents now (Agent tool)"
echo "  Parallel:  1. code-reviewer   2. semantic-reviewer"
echo "             3. doc-updater     4. test-writer"
echo "  Reduced?   Only under a NAMED exemption (CLAUDE.md § Post-commit"
echo "             review) — name it and the condition that qualified it."
echo "  ASYNC:     agents run in the BACKGROUND. Launching four is NOT four"
echo "             reporting. WAIT on every agent you LAUNCHED — never a"
echo "             fixed number, which hangs if fewer were launched — and"
echo "             read every result before fixing anything. Do NOT edit a file"
echo "             while test-writer (the only Write/Edit holder) is in flight."
echo "  Then:      5. learner — AFTER any fixes those results prompted are"
echo "             committed (FULL cycle only — a reduced cycle skips it)"
echo "             On a /crlocal fixup commit, also give it that triage table"
echo "  If security files changed:  6. red-team"
echo "  If rules changed:          7. coderabbit-sync"
echo "  AFTER agents: update spec tasks.md ([ ] → [x])"
echo "  See CLAUDE.md 'Post-commit review' section"
echo "=========================================================="
echo ""
