#!/usr/bin/env bash
echo ""
echo "=========================================================="
echo "  POST-COMMIT: Run subagents now (Agent tool)"
echo "  Parallel:  1. code-reviewer   2. semantic-reviewer"
echo "             3. doc-updater     4. test-writer"
echo "  Reduced?   Only under a NAMED exemption (CLAUDE.md § Post-commit"
echo "             review) — name it and the condition that qualified it."
echo "  Then:      5. learner (FULL cycle only — a reduced cycle skips it)"
echo "  If security files changed:  6. red-team"
echo "  If rules changed:          7. coderabbit-sync"
echo "  AFTER agents: update spec tasks.md ([ ] → [x])"
echo "  See CLAUDE.md 'Post-commit review' section"
echo "=========================================================="
echo ""
