import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { QuizSession } from './quiz-session'

const mockSubmitQuizAnswer = vi.fn()
const mockCompleteQuiz = vi.fn()

vi.mock('../../actions', () => ({
  submitQuizAnswer: (...args: unknown[]) => mockSubmitQuizAnswer(...args),
  completeQuiz: (...args: unknown[]) => mockCompleteQuiz(...args),
}))

const QUESTIONS = [
  {
    id: 'q1',
    question_text: 'What is lift?',
    question_image_url: null,
    options: [
      { id: 'a', text: 'A force' },
      { id: 'b', text: 'A weight' },
      { id: 'c', text: 'A drag' },
    ],
  },
  {
    id: 'q2',
    question_text: 'What is drag?',
    question_image_url: null,
    options: [
      { id: 'd', text: 'Air resistance' },
      { id: 'e', text: 'Thrust' },
    ],
  },
]

describe('QuizSession', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('renders the first question', () => {
    render(<QuizSession sessionId="sess-1" questions={QUESTIONS} />)
    expect(screen.getByText('What is lift?')).toBeInTheDocument()
    expect(screen.getByText('Question 1 of 2')).toBeInTheDocument()
  })

  it('renders answer options for the current question', () => {
    render(<QuizSession sessionId="sess-1" questions={QUESTIONS} />)
    expect(screen.getByText('A force')).toBeInTheDocument()
    expect(screen.getByText('A weight')).toBeInTheDocument()
  })

  it('renders a progress bar', () => {
    const { container } = render(<QuizSession sessionId="sess-1" questions={QUESTIONS} />)
    const progressBar = container.querySelector('.bg-primary.rounded-full')
    expect(progressBar).toBeInTheDocument()
  })

  it('submits an answer and shows feedback', async () => {
    const user = userEvent.setup()
    mockSubmitQuizAnswer.mockResolvedValue({
      success: true,
      isCorrect: true,
      correctOptionId: 'a',
      explanationText: 'Lift is an upward force.',
      explanationImageUrl: null,
    })

    render(<QuizSession sessionId="sess-1" questions={QUESTIONS} />)
    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))

    await waitFor(() => {
      expect(screen.getByText('Lift is an upward force.')).toBeInTheDocument()
    })
    expect(mockSubmitQuizAnswer).toHaveBeenCalledWith(
      expect.objectContaining({
        sessionId: 'sess-1',
        questionId: 'q1',
        selectedOptionId: 'a',
      }),
    )
  })

  it('advances to the next question after feedback', async () => {
    const user = userEvent.setup()
    mockSubmitQuizAnswer.mockResolvedValue({
      success: true,
      isCorrect: true,
      correctOptionId: 'a',
      explanationText: 'Lift is generated by airfoil shape.',
      explanationImageUrl: null,
    })

    render(<QuizSession sessionId="sess-1" questions={QUESTIONS} />)

    // Answer first question
    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))
    await waitFor(() =>
      expect(screen.getByText('Lift is generated by airfoil shape.')).toBeInTheDocument(),
    )

    // Click Next Question
    await user.click(screen.getByRole('button', { name: /Next Question/ }))

    // Second question shown
    expect(screen.getByText('What is drag?')).toBeInTheDocument()
    expect(screen.getByText('Question 2 of 2')).toBeInTheDocument()
  })

  it('shows session summary after the last question', async () => {
    const user = userEvent.setup()
    mockSubmitQuizAnswer.mockResolvedValue({
      success: true,
      isCorrect: true,
      correctOptionId: 'a',
      explanationText: 'OK',
      explanationImageUrl: null,
    })
    mockCompleteQuiz.mockResolvedValue({
      success: true,
      correctCount: 2,
      scorePercentage: 100,
    })

    // Use single question to quickly reach completion
    // QUESTIONS[0] is guaranteed to exist in this test's fixture data
    const singleQ = [QUESTIONS[0] as (typeof QUESTIONS)[0]]
    render(<QuizSession sessionId="sess-1" questions={singleQ} />)

    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))
    await waitFor(() => expect(screen.getByText('OK')).toBeInTheDocument())

    await user.click(screen.getByRole('button', { name: /Next Question/ }))

    await waitFor(() => {
      expect(screen.getByText('100%')).toBeInTheDocument()
    })
    expect(mockCompleteQuiz).toHaveBeenCalledWith({ sessionId: 'sess-1' })
  })

  it('returns null when questions array is empty', () => {
    const { container } = render(<QuizSession sessionId="sess-1" questions={[]} />)
    expect(container.innerHTML).toBe('')
  })
})
