import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { SessionRunner } from './session-runner'
import type { AnswerResult, CompleteResult, SessionQuestion } from './session-runner'

const mockSubmit = vi.fn<(input: unknown) => Promise<AnswerResult>>()
const mockComplete = vi.fn<(input: unknown) => Promise<CompleteResult>>()

const QUESTIONS: SessionQuestion[] = [
  {
    id: 'q1',
    question_text: 'What is lift?',
    question_image_url: null,
    question_number: null,
    options: [
      { id: 'a', text: 'A force' },
      { id: 'b', text: 'A weight' },
      { id: 'c', text: 'A drag' },
    ],
  },
  {
    id: 'q2',
    question_text: 'What is drag?',
    question_image_url: null,
    question_number: null,
    options: [
      { id: 'd', text: 'Air resistance' },
      { id: 'e', text: 'Thrust' },
    ],
  },
]

function renderRunner(questions = QUESTIONS) {
  return render(
    <SessionRunner
      sessionId="sess-1"
      questions={questions}
      onSubmitAnswer={mockSubmit}
      onComplete={mockComplete}
    />,
  )
}

describe('SessionRunner', () => {
  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('renders the first question', () => {
    renderRunner()
    expect(screen.getByText('What is lift?')).toBeInTheDocument()
    expect(screen.getByText('Question 1 of 2')).toBeInTheDocument()
  })

  it('renders answer options for the current question', () => {
    renderRunner()
    expect(screen.getByText('A force')).toBeInTheDocument()
    expect(screen.getByText('A weight')).toBeInTheDocument()
  })

  it('renders a progress bar', () => {
    renderRunner()
    expect(screen.getByTestId('progress-bar')).toBeInTheDocument()
  })

  it('submits an answer and shows feedback', async () => {
    const user = userEvent.setup()
    mockSubmit.mockResolvedValue({
      success: true,
      isCorrect: true,
      correctOptionId: 'a',
      explanationText: 'Lift is an upward force.',
      explanationImageUrl: null,
    })

    renderRunner()
    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))

    await waitFor(() => {
      expect(screen.getByText('Lift is an upward force.')).toBeInTheDocument()
    })
    expect(mockSubmit).toHaveBeenCalledWith(
      expect.objectContaining({
        sessionId: 'sess-1',
        questionId: 'q1',
        selectedOptionId: 'a',
      }),
    )
  })

  it('advances to the next question after feedback', async () => {
    const user = userEvent.setup()
    mockSubmit.mockResolvedValue({
      success: true,
      isCorrect: true,
      correctOptionId: 'a',
      explanationText: 'Lift is generated by airfoil shape.',
      explanationImageUrl: null,
    })

    renderRunner()
    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))
    await waitFor(() =>
      expect(screen.getByText('Lift is generated by airfoil shape.')).toBeInTheDocument(),
    )

    await user.click(screen.getByRole('button', { name: /Next Question/ }))
    expect(screen.getByText('What is drag?')).toBeInTheDocument()
    expect(screen.getByText('Question 2 of 2')).toBeInTheDocument()
  })

  it('shows session summary after the last question', async () => {
    const user = userEvent.setup()
    mockSubmit.mockResolvedValue({
      success: true,
      isCorrect: true,
      correctOptionId: 'a',
      explanationText: 'OK',
      explanationImageUrl: null,
    })
    mockComplete.mockResolvedValue({
      success: true,
      totalQuestions: 1,
      correctCount: 1,
      scorePercentage: 100,
    })

    renderRunner([QUESTIONS[0]!])

    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))
    await waitFor(() => expect(screen.getByText('OK')).toBeInTheDocument())

    await user.click(screen.getByRole('button', { name: /Next Question/ }))

    await waitFor(() => {
      expect(screen.getByText('100%')).toBeInTheDocument()
    })
    expect(mockComplete).toHaveBeenCalledWith({ sessionId: 'sess-1' })
  })

  it('returns null when questions array is empty', () => {
    const { container } = renderRunner([])
    expect(container.innerHTML).toBe('')
  })

  it('shows an error when onSubmitAnswer throws', async () => {
    const user = userEvent.setup({ delay: null })
    const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {})
    mockSubmit.mockRejectedValue(new Error('Network request failed'))

    renderRunner()
    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))

    await waitFor(() => {
      expect(screen.getByRole('alert')).toHaveTextContent('Something went wrong. Please try again.')
    })
    expect(screen.getByText('What is lift?')).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: /Next Question/ })).not.toBeInTheDocument()
    consoleSpy.mockRestore()
  })

  it('shows an error when onComplete throws', async () => {
    const user = userEvent.setup({ delay: null })
    const consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {})
    mockSubmit.mockResolvedValue({
      success: true,
      isCorrect: true,
      correctOptionId: 'a',
      explanationText: 'Lift is an upward force.',
      explanationImageUrl: null,
    })
    mockComplete.mockRejectedValue(new Error('Network timeout'))

    renderRunner([QUESTIONS[0]!])

    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))
    await waitFor(() => expect(screen.getByText('Lift is an upward force.')).toBeInTheDocument())

    await user.click(screen.getByRole('button', { name: /Next Question/ }))

    await waitFor(() => {
      expect(screen.getByRole('alert')).toHaveTextContent('Something went wrong. Please try again.')
    })
    expect(screen.queryByText('100%')).not.toBeInTheDocument()
    consoleSpy.mockRestore()
  })

  it('shows an error when onSubmitAnswer returns failure', async () => {
    const user = userEvent.setup()
    mockSubmit.mockResolvedValue({ success: false, error: 'DB error' })

    renderRunner()
    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))

    await waitFor(() => {
      expect(screen.getByRole('alert')).toHaveTextContent('DB error')
    })
  })

  it('shows an error when onComplete returns failure', async () => {
    const user = userEvent.setup()
    mockSubmit.mockResolvedValue({
      success: true,
      isCorrect: true,
      correctOptionId: 'a',
      explanationText: 'Yes',
      explanationImageUrl: null,
    })
    mockComplete.mockResolvedValue({ success: false, error: 'Session expired' })

    renderRunner([QUESTIONS[0]!])

    await user.click(screen.getByText('A force'))
    await user.click(screen.getByRole('button', { name: 'Submit Answer' }))
    await waitFor(() => expect(screen.getByText('Yes')).toBeInTheDocument())

    await user.click(screen.getByRole('button', { name: /Next Question/ }))

    await waitFor(() => {
      expect(screen.getByRole('alert')).toHaveTextContent('Session expired')
    })
  })
})
