import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ZodError } from 'zod'

// ---- Mocks ----------------------------------------------------------------

const { mockGetUser, mockFrom } = vi.hoisted(() => ({
  mockGetUser: vi.fn(),
  mockFrom: vi.fn(),
}))

vi.mock('@repo/db/server', () => ({
  createServerSupabaseClient: async () => ({
    auth: { getUser: mockGetUser },
    from: mockFrom,
  }),
}))

// ---- Subject under test ---------------------------------------------------

import { fetchExplanation } from './fetch-explanation'

// ---- Fixtures -------------------------------------------------------------

const QUESTION_ID = '00000000-0000-0000-0000-000000000011'
const SESSION_ID = '00000000-0000-0000-0000-000000000099'

function buildSessionChain(override: Record<string, unknown> = {}) {
  const terminal = {
    data: { config: { question_ids: [QUESTION_ID] } },
    error: null,
    ...override,
  }
  return {
    select: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    is: vi.fn().mockReturnThis(),
    single: vi.fn().mockReturnValue(terminal),
  }
}

function buildQuestionChain(override: Record<string, unknown> = {}) {
  const terminal = {
    data: { explanation_text: 'Lift is generated by...', explanation_image_url: null },
    error: null,
    ...override,
  }
  return {
    select: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    is: vi.fn().mockReturnThis(),
    single: vi.fn().mockReturnValue(terminal),
  }
}

function setupAuthenticatedUser() {
  mockGetUser.mockResolvedValue({ data: { user: { id: 'user-1' } } })
}

function setupUnauthenticated() {
  mockGetUser.mockResolvedValue({ data: { user: null } })
}

function setupValidSessionAndQuestionChain(questionOverride: Record<string, unknown> = {}) {
  mockFrom.mockImplementation((table: string) => {
    if (table === 'quiz_sessions') return buildSessionChain()
    return buildQuestionChain(questionOverride)
  })
}

// ---- Lifecycle ------------------------------------------------------------

beforeEach(() => {
  vi.resetAllMocks()
})

// ---- fetchExplanation -----------------------------------------------------

describe('fetchExplanation', () => {
  it('returns failure when user is not authenticated', async () => {
    setupUnauthenticated()
    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })
    expect(result).toEqual({ success: false })
  })

  it('throws a ZodError when questionId is not a valid UUID', async () => {
    setupAuthenticatedUser()
    await expect(
      fetchExplanation({ questionId: 'not-a-uuid', sessionId: SESSION_ID }),
    ).rejects.toThrow(ZodError)
  })

  it('throws a ZodError when questionId is missing', async () => {
    setupAuthenticatedUser()
    await expect(fetchExplanation({})).rejects.toThrow(ZodError)
  })

  it('returns failure when session does not belong to user', async () => {
    setupAuthenticatedUser()
    mockFrom.mockImplementation((table: string) => {
      if (table === 'quiz_sessions')
        return buildSessionChain({ data: null, error: { message: 'not found' } })
      return buildQuestionChain()
    })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({ success: false })
  })

  it('returns failure when questionId is not in session', async () => {
    setupAuthenticatedUser()
    mockFrom.mockImplementation((table: string) => {
      if (table === 'quiz_sessions')
        return buildSessionChain({ data: { config: { question_ids: ['other-id'] } } })
      return buildQuestionChain()
    })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({ success: false })
  })

  it('returns failure when question_ids in config is null (Array.isArray guard)', async () => {
    setupAuthenticatedUser()
    mockFrom.mockImplementation((table: string) => {
      if (table === 'quiz_sessions')
        return buildSessionChain({ data: { config: { question_ids: null } } })
      return buildQuestionChain()
    })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({ success: false })
  })

  it('returns failure when question_ids in config is a plain string (Array.isArray guard)', async () => {
    setupAuthenticatedUser()
    mockFrom.mockImplementation((table: string) => {
      if (table === 'quiz_sessions')
        return buildSessionChain({ data: { config: { question_ids: QUESTION_ID } } })
      return buildQuestionChain()
    })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({ success: false })
  })

  it('returns failure when config itself is null (Array.isArray guard)', async () => {
    setupAuthenticatedUser()
    mockFrom.mockImplementation((table: string) => {
      if (table === 'quiz_sessions') return buildSessionChain({ data: { config: null } })
      return buildQuestionChain()
    })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({ success: false })
  })

  it('returns explanation fields on happy path', async () => {
    setupAuthenticatedUser()
    setupValidSessionAndQuestionChain({
      data: { explanation_text: 'Lift is generated by Bernoulli.', explanation_image_url: null },
      error: null,
    })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({
      success: true,
      explanationText: 'Lift is generated by Bernoulli.',
      explanationImageUrl: null,
    })
  })

  it('returns both explanationText and explanationImageUrl when both are present', async () => {
    setupAuthenticatedUser()
    setupValidSessionAndQuestionChain({
      data: {
        explanation_text: 'See diagram.',
        explanation_image_url: 'https://cdn.example.com/img.png',
      },
      error: null,
    })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({
      success: true,
      explanationText: 'See diagram.',
      explanationImageUrl: 'https://cdn.example.com/img.png',
    })
  })

  it('returns success with null text and null image when both fields are null', async () => {
    setupAuthenticatedUser()
    setupValidSessionAndQuestionChain({
      data: { explanation_text: null, explanation_image_url: null },
      error: null,
    })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({
      success: true,
      explanationText: null,
      explanationImageUrl: null,
    })
  })

  it('returns failure when the database query errors', async () => {
    setupAuthenticatedUser()
    setupValidSessionAndQuestionChain({ data: null, error: { message: 'row not found' } })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({ success: false })
  })

  it('returns failure when data is null (question does not exist or is deleted)', async () => {
    setupAuthenticatedUser()
    setupValidSessionAndQuestionChain({ data: null, error: null })

    const result = await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(result).toEqual({ success: false })
  })

  it('queries only the explanation fields — does not select the full question row', async () => {
    setupAuthenticatedUser()
    let questionChain: ReturnType<typeof buildQuestionChain> | null = null
    mockFrom.mockImplementation((table: string) => {
      if (table === 'quiz_sessions') return buildSessionChain()
      questionChain = buildQuestionChain()
      return questionChain
    })

    await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(questionChain).not.toBeNull()
    expect(questionChain!.select).toHaveBeenCalledWith('explanation_text, explanation_image_url')
  })

  it('filters out soft-deleted questions via deleted_at IS NULL', async () => {
    setupAuthenticatedUser()
    let questionChain: ReturnType<typeof buildQuestionChain> | null = null
    mockFrom.mockImplementation((table: string) => {
      if (table === 'quiz_sessions') return buildSessionChain()
      questionChain = buildQuestionChain()
      return questionChain
    })

    await fetchExplanation({ questionId: QUESTION_ID, sessionId: SESSION_ID })

    expect(questionChain).not.toBeNull()
    expect(questionChain!.is).toHaveBeenCalledWith('deleted_at', null)
  })
})
