import { beforeEach, describe, expect, it, vi } from 'vitest'

// ---- Mocks ----------------------------------------------------------------

const { mockGetUser, mockFrom } = vi.hoisted(() => ({
  mockGetUser: vi.fn(),
  mockFrom: vi.fn(),
}))

vi.mock('@repo/db/server', () => ({
  createServerSupabaseClient: async () => ({
    auth: { getUser: mockGetUser },
    from: mockFrom,
  }),
}))

// ---- Subject under test ---------------------------------------------------

import { fetchExplanation } from './fetch-explanation'

// ---- Fixtures -------------------------------------------------------------

const QUESTION_ID = '00000000-0000-0000-0000-000000000011'

function buildChain(override: Record<string, unknown> = {}) {
  const terminal = {
    data: { explanation_text: 'Lift is generated by...', explanation_image_url: null },
    error: null,
    ...override,
  }
  return {
    select: vi.fn().mockReturnThis(),
    eq: vi.fn().mockReturnThis(),
    is: vi.fn().mockReturnThis(),
    single: vi.fn().mockReturnValue(terminal),
  }
}

function setupAuthenticatedUser() {
  mockGetUser.mockResolvedValue({ data: { user: { id: 'user-1' } } })
}

function setupUnauthenticated() {
  mockGetUser.mockResolvedValue({ data: { user: null } })
}

// ---- Lifecycle ------------------------------------------------------------

beforeEach(() => {
  vi.resetAllMocks()
})

// ---- fetchExplanation -----------------------------------------------------

describe('fetchExplanation', () => {
  it('returns failure when user is not authenticated', async () => {
    setupUnauthenticated()
    const result = await fetchExplanation({ questionId: QUESTION_ID })
    expect(result).toEqual({ success: false })
  })

  it('throws a ZodError when questionId is not a valid UUID', async () => {
    setupAuthenticatedUser()
    await expect(fetchExplanation({ questionId: 'not-a-uuid' })).rejects.toThrow()
  })

  it('throws a ZodError when questionId is missing', async () => {
    setupAuthenticatedUser()
    await expect(fetchExplanation({})).rejects.toThrow()
  })

  it('returns explanation fields on happy path', async () => {
    setupAuthenticatedUser()
    const chain = buildChain({
      data: { explanation_text: 'Lift is generated by Bernoulli.', explanation_image_url: null },
      error: null,
    })
    mockFrom.mockReturnValue(chain)

    const result = await fetchExplanation({ questionId: QUESTION_ID })

    expect(result).toEqual({
      success: true,
      explanationText: 'Lift is generated by Bernoulli.',
      explanationImageUrl: null,
    })
  })

  it('returns both explanationText and explanationImageUrl when both are present', async () => {
    setupAuthenticatedUser()
    const chain = buildChain({
      data: {
        explanation_text: 'See diagram.',
        explanation_image_url: 'https://cdn.example.com/img.png',
      },
      error: null,
    })
    mockFrom.mockReturnValue(chain)

    const result = await fetchExplanation({ questionId: QUESTION_ID })

    expect(result).toEqual({
      success: true,
      explanationText: 'See diagram.',
      explanationImageUrl: 'https://cdn.example.com/img.png',
    })
  })

  it('returns success with null text and null image when both fields are null', async () => {
    setupAuthenticatedUser()
    const chain = buildChain({
      data: { explanation_text: null, explanation_image_url: null },
      error: null,
    })
    mockFrom.mockReturnValue(chain)

    const result = await fetchExplanation({ questionId: QUESTION_ID })

    expect(result).toEqual({
      success: true,
      explanationText: null,
      explanationImageUrl: null,
    })
  })

  it('returns failure when the database query errors', async () => {
    setupAuthenticatedUser()
    const chain = buildChain({ data: null, error: { message: 'row not found' } })
    mockFrom.mockReturnValue(chain)

    const result = await fetchExplanation({ questionId: QUESTION_ID })

    expect(result).toEqual({ success: false })
  })

  it('returns failure when data is null (question does not exist or is deleted)', async () => {
    setupAuthenticatedUser()
    const chain = buildChain({ data: null, error: null })
    mockFrom.mockReturnValue(chain)

    const result = await fetchExplanation({ questionId: QUESTION_ID })

    expect(result).toEqual({ success: false })
  })

  it('queries only the explanation fields — does not select the full question row', async () => {
    setupAuthenticatedUser()
    const chain = buildChain()
    mockFrom.mockReturnValue(chain)

    await fetchExplanation({ questionId: QUESTION_ID })

    expect(chain.select).toHaveBeenCalledWith('explanation_text, explanation_image_url')
  })

  it('filters out soft-deleted questions via deleted_at IS NULL', async () => {
    setupAuthenticatedUser()
    const chain = buildChain()
    mockFrom.mockReturnValue(chain)

    await fetchExplanation({ questionId: QUESTION_ID })

    expect(chain.is).toHaveBeenCalledWith('deleted_at', null)
  })
})
